### ISSUE TITLE
Mobile & Cordova

### ISSUE THREAD

**Issue by Hamatek** [brentjanderson/meteor-buzz#9]
Hello,

Awesome meteor package i love it, i'm just facing some issue on mobile i have I think something like 500ms delay between a click event and the sound, I think its  due to the fastclick package that remove the delay on click event on mobile, do you guys have any idea how to fix that ?

Also on cordova android sound doesn't play at all, there is some talks on SO http://stackoverflow.com/questions/27432554/play-sound-in-meteor-cordova-app

and there is  some package on atmospherejs https://atmospherejs.com/adej/meteor-sounds

but I was wondering how do you guys deal with this issues ? is there an easy workaround with meteor-buzz ?

Cheers

**Comment by brentjanderson** [comment]
I don't do cordova android builds, and therefore haven't tried this out. That said, it sounds like you could use the instructions in that SO article with Buzz just fine. This URL example from that article should work fine when loading Buzz assets: `/android_asset/www/application/path/to/sound.wav`.

As for the gap between the click event and the sound firing, that is likely an issue with mobile touch event detection (see http://www.sitepoint.com/5-ways-prevent-300ms-click-delay-mobile-devices/ for details). Fastclick is supposed to remove that issue, however I don't have other guidance on removing that issue, as the issue is not part of Buzz.js specifically but parto f the platform as a whole.
